# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=10000, verbose_name='Post Description')),
                ('category', models.CharField(max_length=50, verbose_name='Post Category')),
                ('media', models.FileField(upload_to='<built-in function id>/', verbose_name='Post Media file')),
            ],
            options={
                'verbose_name': 'Facebook Posts',
                'verbose_name_plural': 'Facebook Posts',
            },
        ),
    ]
